version: '2'

services:
  audioapi:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  db:
    image: mysql:5.7
    restart: always
    hostname: audio_db
    environment:
      MYSQL_DATABASE: 'audio_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db:

networks:
  gateway:
    driver: bridge
