version: '2'

services:
  audioapi_test:
    build:
      context: ./src
      dockerfile: Dockerfile
      args:
        DB_USER: user
        DB_PASS: password
        DB_HOST: test_db
        DB_NAME: audio_db
        FILE_DIRECTORY: /test-data
    depends_on:
      - test_db
    ports:
      - "8080:8080"
    volumes:
      - test-data:/test-data/
    
  test_db:
    image: mysql:5.7
    restart: always
    hostname: test_db
    environment:
      MYSQL_DATABASE: 'audio_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - test-db:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    logging:
      driver: "none"

  test-client:
    build:
      context: ./
      dockerfile: ./test/Dockerfile
      args:
        SRC_ROOT: ./src
        TEST_ROOT: ./test

volumes:
  test-data:
  test-db: